Civil-Service-Human-Resources/lpg-learning-catalogue

- src/main/java/uk/gov/cslearning/catalogue/api/SearchController.java
- src/main/java/uk/gov/cslearning/catalogue/api/SearchResults.java
- src/main/java/uk/gov/cslearning/catalogue/domain/SearchPage.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseRepository.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSearchRepository.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSearchRepositoryImpl.java
- src/test/java/uk/gov/cslearning/catalogue/repository/CourseSearchRepositoryIT.java
Adding pagination to search controller
> feature/634 - adding pagination to search

- src/main/java/uk/gov/cslearning/catalogue/api/FilterParameters.java
- src/main/java/uk/gov/cslearning/catalogue/api/SearchController.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseRepository.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSearchRepository.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSearchRepositoryImpl.java
- src/test/java/uk/gov/cslearning/catalogue/repository/CourseSearchRepositoryIT.java
New PR as Travis doesnt seem to pick up changed tests ...
> Lpfg 40 search results filtering

- src/main/java/uk/gov/cslearning/catalogue/domain/module/Event.java
**PR includes:**
* (maximum) Capacity property for Event type
> LPFG-416 (+1 squashed commit)

- src/main/java/uk/gov/cslearning/catalogue/api/CourseController.java
- src/main/java/uk/gov/cslearning/catalogue/domain/module/Audience.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseRepository.java
> Update audiences to include interests

- build.gradle
- docker-compose.yml
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/uk/gov/cslearning/catalogue/api/ApiExceptionHandler.java
- src/main/java/uk/gov/cslearning/catalogue/api/CourseController.java
- src/main/java/uk/gov/cslearning/catalogue/api/FilterParameters.java
- src/main/java/uk/gov/cslearning/catalogue/api/PageResults.java
- src/main/java/uk/gov/cslearning/catalogue/config/SwaggerConfig.java
- src/main/java/uk/gov/cslearning/catalogue/config/WebConfiguration.java
- src/main/java/uk/gov/cslearning/catalogue/repository/PurchaseOrderRepository.java
- src/main/java/uk/gov/cslearning/catalogue/repository/ResourceRepository.java
- src/main/java/uk/gov/cslearning/catalogue/service/ModuleService.java
- src/test/java/uk/gov/cslearning/catalogue/api/CourseControllerTest.java
- src/test/java/uk/gov/cslearning/catalogue/service/ModuleServiceTest.java
Added ModuleController to find and create modules individually on a course.
> LPFG-570: Add Module (Blogs)

- src/main/java/uk/gov/cslearning/catalogue/api/CourseController.java
- src/main/java/uk/gov/cslearning/catalogue/domain/module/DateRange.java
- src/main/java/uk/gov/cslearning/catalogue/domain/module/Event.java
- src/main/java/uk/gov/cslearning/catalogue/domain/module/Venue.java
- src/test/java/uk/gov/cslearning/catalogue/api/CourseControllerTest.java
- src/test/java/uk/gov/cslearning/catalogue/domain/module/DateRangeTest.java
- src/test/java/uk/gov/cslearning/catalogue/domain/module/VenueTest.java
Fixed bug. Set venue when updating events.
> LPFG-678: Edit location & availability

- build.gradle
- src/main/java/uk/gov/cslearning/catalogue/domain/Status.java
- src/main/java/uk/gov/cslearning/catalogue/exception/UnknownStatusException.java
- src/test/java/uk/gov/cslearning/catalogue/domain/StatusTest.java
- src/test/resources/course.json
Added Jackson annotations to Status enum
> LPFG-889: Add status field to domain classes in lpg-management

- src/main/java/uk/gov/cslearning/catalogue/api/CourseController.java
- src/main/java/uk/gov/cslearning/catalogue/domain/Course.java
- src/main/java/uk/gov/cslearning/catalogue/service/ModuleService.java
- src/test/java/uk/gov/cslearning/catalogue/api/CourseControllerTest.java
- src/test/java/uk/gov/cslearning/catalogue/domain/CourseTest.java
- controller mapping to delete a module by moduleId
> LPFG-846: delete module method and tests

- src/main/java/uk/gov/cslearning/catalogue/repository/CourseRepository.java
Enter a department with d12 and observer term analyzer won't match because it analyzes strings only
> [LPFG-1039][LPFG-1042][BUG] Catalogue won't match integer fields

- .gitignore
- src/main/java/uk/gov/cslearning/catalogue/api/MediaController.java
- src/main/java/uk/gov/cslearning/catalogue/api/ReportController.java
- src/main/java/uk/gov/cslearning/catalogue/config/UploadConfig.java
- src/main/java/uk/gov/cslearning/catalogue/dto/EventDto.java
- src/main/java/uk/gov/cslearning/catalogue/dto/ModuleDto.java
- src/main/java/uk/gov/cslearning/catalogue/dto/factory/EventDtoFactory.java
- src/main/java/uk/gov/cslearning/catalogue/dto/factory/ModuleDtoFactory.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseRepository.java
- src/main/java/uk/gov/cslearning/catalogue/service/ModuleService.java
- src/main/java/uk/gov/cslearning/catalogue/service/record/LearnerRecordService.java
- src/main/java/uk/gov/cslearning/catalogue/service/record/RequestEntityFactory.java
- src/main/java/uk/gov/cslearning/catalogue/service/upload/processor/ScormFileProcessor.java
- src/main/java/uk/gov/cslearning/catalogue/service/upload/processor/XPathProcessor.java
- src/test/java/uk/gov/cslearning/catalogue/api/ReportControllerTest.java
- src/test/java/uk/gov/cslearning/catalogue/config/UploadConfigTest.java
- src/test/java/uk/gov/cslearning/catalogue/dto/factory/EventDtoFactoryTest.java
- src/test/java/uk/gov/cslearning/catalogue/dto/factory/ModuleDtoFactoryTest.java
- src/test/java/uk/gov/cslearning/catalogue/service/EventServiceTest.java
- src/test/java/uk/gov/cslearning/catalogue/service/ModuleServiceTest.java
- src/test/java/uk/gov/cslearning/catalogue/service/upload/processor/ScormFileProcessorTest.java
- src/test/java/uk/gov/cslearning/catalogue/service/upload/processor/XPathProcessorTest.java
Added /reporting/modules endpoint to return all modules as a map with id as key.
> LPFG-290: MI: CSV file to extract data - Learner record

- src/main/java/uk/gov/cslearning/catalogue/api/ProfileParameters.java
- src/main/java/uk/gov/cslearning/catalogue/api/SearchController.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseRepository.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSearchRepository.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSearchRepositoryImpl.java
- src/test/java/uk/gov/cslearning/catalogue/api/SearchControllerTest.java
- src/test/java/uk/gov/cslearning/catalogue/repository/CourseSearchRepositoryIT.java
- replacing https://github.com/Civil-Service-Human-Resources/lpg-learning-catalogue/pull/82
> LPFG-1213: course-visibility-v2

- src/main/java/uk/gov/cslearning/catalogue/api/CourseController.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseRepository.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSuggestionsRepository.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSuggestionsRepositoryImpl.java
- src/test/java/uk/gov/cslearning/catalogue/api/CourseControllerTest.java
- replacing https://github.com/Civil-Service-Human-Resources/lpg-learning-catalogue/pull/74/
> LPFG-1048-Suggestions-Showing-Incorrect-Learning-v2

- src/main/java/uk/gov/cslearning/catalogue/domain/Course.java
- src/main/java/uk/gov/cslearning/catalogue/domain/Frequency.java
- src/main/java/uk/gov/cslearning/catalogue/domain/module/Audience.java
- replacing https://github.com/Civil-Service-Human-Resources/lpg-learning-catalogue/pull/85
> LPFG-1238: pre-reading-audience-v2

- src/main/java/uk/gov/cslearning/catalogue/api/ReportController.java
- src/main/java/uk/gov/cslearning/catalogue/domain/Roles.java
- adding endpoint for kornferry reports
> LC-157: kf reporter endpoint

- src/main/java/uk/gov/cslearning/catalogue/config/SwaggerConfig.java
- fixing issue with swagger/springfox compilation
> chore: fix-swagger-compile-issue

- src/main/java/uk/gov/cslearning/catalogue/api/CourseController.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSuggestionsRepository.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSuggestionsRepositoryImpl.java
- src/test/java/uk/gov/cslearning/catalogue/api/CourseControllerTest.java
- updating search to include grade filter
> LC-191: updating search to include grade filter

- src/main/java/uk/gov/cslearning/catalogue/api/ReportController.java
- src/main/java/uk/gov/cslearning/catalogue/service/ModuleService.java
> fix-supplier-modules-report

- src/main/java/uk/gov/cslearning/catalogue/api/CourseController.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSuggestionsRepositoryImpl.java
- src/test/java/uk/gov/cslearning/catalogue/api/CourseControllerTest.java
- filtering suggestions to ensure filtered by grade
> fix-update-suggestions-to-avoid-overlap

- src/main/java/uk/gov/cslearning/catalogue/config/ElasticSearchConfig.java
- src/main/java/uk/gov/cslearning/catalogue/config/ElasticSearchProperties.java
- src/main/resources/application.yml
- update jest/elastic timeout from default of 3s to 10s to avoid readTimeout exceptions
> LC-217: updating elastic readTimeout config 

- src/main/java/uk/gov/cslearning/catalogue/api/CourseController.java
- src/main/java/uk/gov/cslearning/catalogue/api/SearchController.java
- src/main/java/uk/gov/cslearning/catalogue/domain/CivilServant/OrganisationalUnit.java
- src/main/java/uk/gov/cslearning/catalogue/exception/IllegalTypeException.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSuggestionsRepository.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSuggestionsRepositoryImpl.java
- src/main/java/uk/gov/cslearning/catalogue/service/AuthoritiesService.java
- src/main/java/uk/gov/cslearning/catalogue/service/CourseService.java
- src/main/java/uk/gov/cslearning/catalogue/service/ParameterizedTypeReferenceFactory.java
- src/main/java/uk/gov/cslearning/catalogue/service/RegistryService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/cslearning/catalogue/api/CourseControllerTest.java
- src/test/java/uk/gov/cslearning/catalogue/api/SearchControllerTest.java
- get parent organisation hierarchy from csrs
- update suggestions to get by multiple departments
> LC-240: cascade-suggestions-to-sub-divisions

- src/main/java/uk/gov/cslearning/catalogue/api/CourseController.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseRepository.java
- src/main/java/uk/gov/cslearning/catalogue/service/CourseService.java
- src/main/java/uk/gov/cslearning/catalogue/service/ParameterizedTypeReferenceFactory.java
- src/main/java/uk/gov/cslearning/catalogue/service/RegistryService.java
- src/main/java/uk/gov/cslearning/catalogue/service/RequiredByService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/cslearning/catalogue/api/CourseControllerTest.java
- src/test/java/uk/gov/cslearning/catalogue/service/CourseServiceTest.java
- src/test/java/uk/gov/cslearning/catalogue/service/RequiredByServiceTest.java
- adding new endpoint to get required learning of multiple orgs
> fix: ading new endpoint to get required learning of multiple orgs

- Dockerfile
- build.gradle
- lib/AI-Agent.xml
- src/main/resources/ApplicationsInsights.xml
enable MS Application Insights
> add Azure App Insights

- src/main/java/uk/gov/cslearning/catalogue/domain/module/Module.java
- src/main/java/uk/gov/cslearning/catalogue/dto/ModuleDto.java
- src/main/java/uk/gov/cslearning/catalogue/dto/factory/ModuleDtoFactory.java
- https://cshrdigitalandanalysis.atlassian.net/browse/LC-235
- add new associated learning attribute to module entity
- replacing https://github.com/Civil-Service-Human-Resources/lpg-learning-catalogue/pull/116/files
> LC-234 - add new associated learning attribute to module entity

- src/main/java/uk/gov/cslearning/catalogue/config/OAuthProperties.java
- src/main/java/uk/gov/cslearning/catalogue/config/SecurityConfig.java
- src/main/resources/application.yml
Added "PoolingHttpClientConnectionManager" to be used by OAuth2RestTemplate in order to increase its efficiency. The manager is also configurable.
> Implemented PoolingHttpClientConnectionManager to be used for requests

- src/main/java/uk/gov/cslearning/catalogue/dto/EventDto.java
- src/main/java/uk/gov/cslearning/catalogue/dto/factory/EventDtoFactory.java
- src/test/java/uk/gov/cslearning/catalogue/dto/factory/EventDtoFactoryTest.java
**Jira Ticket:** 
https://cshrdigitalandanalysis.atlassian.net/browse/LC-280
https://cshrdigitalandanalysis.atlassian.net/browse/LC-309
This branch adds booking reference, event location, event ID and event date. 
This branch is used by: 
https://github.com/Civil-Service-Human-Resources/lpg-report-service/pull/26
> added location, event date, booking ID and event ID to the MI report

- src/main/java/uk/gov/cslearning/catalogue/domain/module/DateRange.java
- src/main/java/uk/gov/cslearning/catalogue/dto/factory/EventDtoFactory.java
- src/main/java/uk/gov/cslearning/catalogue/service/util/DateRangeComparator.java
- src/test/java/uk/gov/cslearning/catalogue/domain/module/DateRangeTest.java
- src/test/java/uk/gov/cslearning/catalogue/dto/factory/EventDtoFactoryTest.java
- src/test/java/uk/gov/cslearning/catalogue/service/util/DateRangeComparatorTest.java
Ordering of event dates in F2F course modules.
> Lc 237 multiple dates ordering

- src/main/java/uk/gov/cslearning/catalogue/domain/module/DateRange.java
- src/main/java/uk/gov/cslearning/catalogue/dto/EventDto.java
- src/main/java/uk/gov/cslearning/catalogue/dto/factory/EventDtoFactory.java
- src/main/java/uk/gov/cslearning/catalogue/service/util/DateRangeComparator.java
- src/test/java/uk/gov/cslearning/catalogue/domain/module/DateRangeTest.java
- src/test/java/uk/gov/cslearning/catalogue/dto/factory/EventDtoFactoryTest.java
- src/test/java/uk/gov/cslearning/catalogue/service/util/DateRangeComparatorTest.java
Release branch for face-to-face features. Contains PRs:
https://github.com/Civil-Service-Human-Resources/lpg-learning-catalogue/pull/121
https://github.com/Civil-Service-Human-Resources/lpg-learning-catalogue/pull/123
https://github.com/Civil-Service-Human-Resources/lpg-learning-catalogue/pull/125
> Releases - F2F features

- src/main/java/uk/gov/cslearning/catalogue/api/CourseController.java
- src/test/java/uk/gov/cslearning/catalogue/api/CourseControllerTest.java
> Feature lc 586 suggested learning fix

- src/main/java/uk/gov/cslearning/catalogue/api/HealthController.java
- src/main/java/uk/gov/cslearning/catalogue/config/SecurityConfig.java
This change:
* Creates a healthcheck endpoint, `/health`
* Updates the security configuration for the endpoint
> Healthcheck endpoint

- .run/Docker remote debug.run.xml
- .run/lpg-learning-catalogue [bootRun].run.xml
- Dockerfile.dev
- src/main/java/uk/gov/cslearning/catalogue/service/CourseService.java
- src/main/java/uk/gov/cslearning/catalogue/service/EventService.java
- src/main/java/uk/gov/cslearning/catalogue/service/record/LearnerRecordService.java
- src/main/java/uk/gov/cslearning/catalogue/service/record/model/Event.java
- src/main/resources/application.yml
- src/test/java/uk/gov/cslearning/catalogue/service/CourseServiceTest.java
- src/test/java/uk/gov/cslearning/catalogue/service/EventServiceTest.java
- src/test/java/uk/gov/cslearning/catalogue/service/record/LearnerRecordServiceTest.java
- Added non-breakning files from `LC-feature-XXX-local-development`
- Event availability now makes use of the new `GET /events-list` endpoint in learner-record. This batches up events and processes them all in the learning-catalogue to figure out the availability of events, amongst other things
> Idt feature lc 1092 refactor course overview events

- .dockerignore
- Dockerfile.dev
- src/main/java/uk/gov/cslearning/catalogue/api/SearchController.java
- src/main/java/uk/gov/cslearning/catalogue/api/v2/CourseControllerV2.java
- src/main/java/uk/gov/cslearning/catalogue/api/v2/model/CourseSearchParameters.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSearchRepository.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSearchRepositoryImpl.java
- src/test/java/uk/gov/cslearning/catalogue/domain/CourseSearchParametersTest.java
This change:
* Creates a new endpoint `/v2/courses/search`
* Creates a new `search()` method in `CourseSearchRepository` called by the new endpoint
* Creates a new model class `CourseSearchParameters`, containing the parameters of the new method (search term, cost, departments etc).
* Creates a new test class `CourseSearchParametersTest`, which contains 4 new test methods.
* Updates the version of Gradle to 6.8 in `Dockerfile.dev`
> LC-2349: Search filter bug fix - Your department  

- src/main/java/uk/gov/cslearning/catalogue/api/v2/model/CourseSearchParameters.java
- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSearchRepositoryImpl.java
This change adds learning types to the search query.
> Fix learning types search filter

- src/main/java/uk/gov/cslearning/catalogue/repository/CourseSearchRepositoryImpl.java
This change adds an additional filter for search so that search results only show public courses
> LC-2737: Add visibility filter
